### ISSUE TITLE
USER STORY: Django and Gitpod Setup

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#1]
As a developer I can use Gitpod in tandem with Django to set up the structure of my project. 

**Acceptance criteria**

- Create workspace for Oodles of Comfort in Gitpod. 
- Install Django and set up initial project structure. 

**Tasks**

- [x] Clone repository from GitHub to GitPod
- [x] Install Django and initialise project.
- [x] Set up env.py to hide secret keys and add to .gitignore
- [x] Test that app will display Django landing page for app when running server.
