### ISSUE TITLE
USER STORY: Recipe Post Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#10]
As a user I can view a particular recipe to get more information on it such as the prep time, cook time, ingredients and how to prepare the recipe. I can also see the end result through an image of the recipe.

**Acceptance criteria**

- Further information on recipe, such as the ingredients and how to make. 
- Must be clear and concise to the user. 
- An image of the recipe must be included. 

**Tasks**

- [x] Create a recipe_detail.html which extends the base.html
- [x] Create a clear layout for recipe and include all necessary information from the database to cook the recipe. 
- [x] Correct image for the recipe must be pulled from database. 
- [x] Finalise CSS/Design for page
