### ISSUE TITLE
USER STORY: Recipe List Page 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#10]
As a user I can see a list of all of the recipes available to me on this site, I can search for a specific recipe, filter by tags such as recipes with little to no spice, very spice recipes, vegetarian friendly recipes and vegan friendly recipes. 

**Acceptance criteria** 

- I want to be able to search the entire list of recipes to find a specific recipe.
- I want to filter the recipes by various tags 
- I want to be able to scroll through the list of recipes easily
- I would like there to be a small image of the recipe as I am searching.

**Tasks** 

- [ ] Add a search function to the recipe list to locate any recipe in the database. 
- [ ] Add tags to the recipes for finer filtering.
- [ ] Scroll bar to look through all of the recipes before or after filtering.
- [ ] Display the recipes on small cards with an image for a more user friendly search.
