### ISSUE TITLE
USER STORY: 404 Page 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#11]
As a user I can see a 404 error page when there has been a problem with the site directing me to a page or when there is an general error, I can see a link which brings me safely back to the home page. 

**Acceptance criteria** 

- I want the site to display a 404 error to me if there has been an issue navigating the site. 
- There should be an easily accessible link directing me back to the home page. 

**Tasks**

- [ ] Create 404.html which extends the base.html.
- [ ] It should be clear from the design and layout of the page that this is a 404 page. 
- [ ] Add a link to bring the user back to the home page.
