### ISSUE TITLE
USER STORY: README - Design

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#14]
As a developer I can document the design phase of the project, from the initial wireframe designs to colour, font and overall site design planning. 

**Tasks**

- [x] Add desktop wireframes to README
- [x] Add mobile wireframes to README
- [x] Add colour scheme to README
- [x] Add font choices to README
