### ISSUE TITLE
USER STORY: Add navigation

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#15]
As a user I can navigate through the site easily, this can be done on any page and is easily accessible. 

**Acceptance criteria** 

- It must be easy to navigate to any page on the site. 
- Navbar must be accessible even when scrolling through the page - essential for ease of use on mobile

**Tasks**

- [ ] Add a navbar to the top of the page using bootstrap. 
- [ ] Make navbar sticky to that it can be used even when scrolling through the site.
- [ ] Navbar must be same on each page.
