### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#17]
As a user I can navigate the blog through a navbar located at the top of the page, from here I can access the home page and recipe list I can also log in to my account from here or create an account if I have not yet done so.

**Acceptance criteria**

- A navbar must be at the top of the page to allow for easy access and navigation throughout the site. 
- There must be links for home and recipe list. 
- User must also be able to log in/create an account from the navbar

**Tasks**

- [x] Create an includes folder in the directory.
- [x] Create header.html for the navbar and link to it in the base.html using 'includes'
- [x] Add links to the index.html, recipe_list.html
- [x] Add option to Log in/Sign up to the blog.
