### ISSUE TITLE
USER STORY: Recipe card carousel

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#18]
As a user I can see a selection of recipes as cards on the main page, these change automatically. I can click on one of these cards to view the full recipe page. 

**Acceptance criteria**

- Cards should display clearly what recipe they are for.
- Recipes should change automatically
- Clicking on a recipe card should direct user to full recipe page. 

**Tasks**

- [x] Create cards to display the ramen recipes from database
- [x] Set random recipes to display - max of 5
- [x] Display matching recipe when a recipe card is selected.
