### ISSUE TITLE
USER STORY: Footer

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#19]
As a user I can access various social media platforms for Oodles of Comfort, I can see their Instagram, YouTube, X or Facebook account and view them easily. 

**Acceptance criteria**

- Clear and easily accessible footer
- Links bring to the correct respective sites

**Tasks**

- [x] Create a footer.html within the includes folder
- [x] Add icons for various social media platforms
- [x] Make each icon a clickable link to the correct social media site.
