### ISSUE TITLE
USER STORY: Deploy to Heroku 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#2]
As a developer I can deploy my project to Heroku after the initial set up to ensure that everything works correctly and can test the project as a develop it. 

**Acceptance criteria**
- App live link must work correctly without any errors displaying to the console. 

**Tasks** 

- [x] Create an app for Oodles of Comfort on Heroku.
- [x] Add the secret keys to config values.
- [x] Set up requirments.txt file. 
- [x] Create Heroku Procfile
- [x] Deploy to main branch
