### ISSUE TITLE
USER STORY: Setup and connect database

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#2]
As a developer I will need to setup and connect a database to this project in order to securely store the user's information

**Tasks** 
 - [ ] Configure Django settings with database.
 - [ ] Set up superuser for admin panel.
 - [ ] Configure static files.
