### ISSUE TITLE
USER STORY: User Profile Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#20]
As a user I can view my own profile page when I am logged into the site, from here I can see my information that I have provided and wish to have public. I can see the last recipe I viewed and I can also view my comments/liked recipes. 

**Acceptance criteria**

- User page only visible when logged in. 
- Can only see information that user wants displayed - email address must be hidden.
- Can view the last recipe that was looked at.
- Can view most recent comments. 
- Can check liked recipes

**Tasks**

- [x] Create Users app
- [x] Build Users model
- [x] Create user_profile.html which extends base.html
- [x] Allow page to only be accessed if user is logged in. 
- [x] Display username, profile picture and date account was created

Due to time constraints these tasks will be implemented in a future iteration
- [ ] Display recently viewed recipe to page.
- [ ] Display most recent comments
- [ ] View liked recipes on page as well.
