### ISSUE TITLE
USER STORY: Log In 

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#22]
As a user who has an account on this site I want to be able to easily log in, there should be an option to log in on the navigation bar which can be accessed from any page. 

**Acceptance criteria**

- A user who has an account must be able to easily log in to the site. 
- Log in button should be accessible on the navigation bar
- Navigation bar must update to display sign out if a user is logged in. 

**Tasks**

- [x] Add a log in button to the navbar
- [x] Add prompts to enter log in details. 
- [x] Update navigation bar to display sign out button when a user is logged in.
