### ISSUE TITLE
USER STORY: Recipe Tags

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#24]
As a user I can search for recipes based on tags to fine tune my search when on the recipe_list page. 

**Acceptance criteria**

- There must be a search bar on the recipe list page which can search by tags. 
- Tags model must be connected to the Recipe model.

**Tasks**

- [x] Create a Tags model in the blog app. 
- [x] Link Tags model to Recipe model as a ForeignKey.
- [ ] Implement Tags in a search feature.
