### ISSUE TITLE
User Story: README - Design Methodologies

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#25]
As a developer I can build a project using agile development, this allows for proper planning of the project to ensure design scope meets the user goals. 

**Tasks**

- [ ] Discuss Agile development as a methodology
- [ ] Add Epics to README 
- [ ] Discuss EPICS and their relation to User Stories
