### ISSUE TITLE
USER STORY: Deploy to Heroku

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#3]
As a developer I will deploy the application to Heroku early to ensure that everything was set up correctly and to allow accurate testing as the project is being developed. 

**Tasks** 
- [ ] Create a new app on Heroku
- [ ] Add secret keys to app config
- [ ] Create requirements.txt file to manage all installed packages
- [ ] Create Procfile for Heroku
- [ ] Deploy to Heroku
