### ISSUE TITLE
USER STORY: Create wireframes

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#4]
As a developer I will create wireframes to establish a layout for each page of the site to ensure a coherent design. 

**Tasks** 
- [ ] Create wireframe for home page
- [ ] Create wireframe for user login
- [ ] Create wireframe for 404 page
- [ ] Create wireframe for list of recipes
- [ ] Create wireframe for user profile page
- [ ] Create wireframe for recipe page
