### ISSUE TITLE
USER STORY: Home page design

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#7]
As a user I can see a main banner for the home page with site logo, an about section so I can know what the website is about, and a scrollable carousel of images showing me the top recipes so I can navigate to those easily. 

**Acceptance criteria** 

-  I want to see a banner image with the site logo so I instantly know what site I'm on
- I want to see an about section so I can learn more about the site
- I want to see a selection of top 5 recipes so I can easily redirect to those immediately

**Tasks**
- [ ] Create a base.html
- [ ] Create an index.html which extends the base.html
- [ ] Create an about section which describes the purpose of the site
- [ ] Create a carousel of images which cycles on hover, displaying top 5 recipes. 
- [ ] Each image for carousel is a clickable link to the recipe's page
