### ISSUE TITLE
USER STORY: Home page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#8]
As a user I can view the home page for this site, once here I can view a selection of recipes, navigate to other pages and log in to the site or I can create an account. 

**Acceptance criteria**

- The home page must display a selection of recipes from the database for the user. 
- It must be possible to navigate to other pages from the home. 
- A user must be able to log in to their account or create an account from here. 

**Tasks**

- [x] Create a index.html which extends the base.html
- [x] Display a random selection of recipes to the home page. 
- [x] Add a navigation bar to the home page to access other pages. 
- [x] Add log in button to navigation bar
- [x] Finalise CSS/Design for page
