### ISSUE TITLE
USER STORY:  Recipe List Page

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#9]
As a user I can access and view a list of all ramen recipes, I can search in this list for a particular recipe or I can even filter the list by various tags such as vegan friendly recipes.

**Acceptance criteria**

- All recipes displayed in an easy to navigate list. 
- A search feature to look for particular recipes. 
- Ability to filter through the recipe list by tags

**Tasks**

- [x] Create a recipe_list.html which extends the base.html
- [x] Add a search function to list of recipes. 

Due to time constraints this feature will be added in the next iteration
- [ ] Add tags to filter through the recipes to refine the list.
