### ISSUE TITLE
USER STORY: User Profile Design

### ISSUE THREAD

**Issue by ZoeMacf** [ZoeMacf/oodles-of-comfort#9]
As a user I can view my profile page, here I can see the information that I have entered and my most recent recipes which I liked.

Acceptance criteria 

- I want to be able to view my profile page with a user icon and user info
- I would like to see my most recent liked recipes

**Tasks**
- [ ] Create user_page.html which extends base.html
- [ ] Assign a picture to user which will be displayed on the page. 
- [ ] Display user information for correct user
- [ ] Display most recent four recipes liked by user.
